config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.order(upvotes: :desc).all
	end

	def update
		@article = Article.find(params[:id])
		upvotes = @article.upvotes+1
		@article.update_attributes(upvotes:upvotes)
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
    <div class="header">
      <div class="container">
        <h1>readme</h1>
      </div>
    </div>

    <div class="main">
      <div class="container">
        <ul class="articles">
          <% @articles.each do |a| %>
          <li>
            <%= link_to "", article_path(a), method: :put, class: "fa fa-caret-up" %>
            <span class="upvotes"> <%= a.upvotes %> </span>
            <a class="title" href="<%= a.url %>"><%= a.title %></a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Readme</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>